/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Clases.Lista;
import Clases.ListaResumen;
import Clases.Main;
import Clases.NodoResumen;
import Info.LeerTxt;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author verol
 */
public class VentanaAnalisis extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAnalisis
     */
    public static Ventana2 v22;
     private void inicializarJList() {
        resumenesLista.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 1) { // Detecta un solo clic
                    int index = resumenesLista.locationToIndex(e.getPoint());
                    if (index >= 0) {
                        ListaResumen resumenesEncontrados = Main.txt.listaDeResumenes;
                        int contador = 0;
                        NodoResumen aux = resumenesEncontrados.getFirst();
                        while (contador != index && aux != null) {
                            aux = aux.getNext();
                            contador++;
                        }
                        if (aux != null) {
                        VentanaMostrarAnalisis vma = new VentanaMostrarAnalisis(aux.getInfo());
                        vma.setVisible(true);
                        
                        }
                    }
                }
            }
        });
     }
    
    public VentanaAnalisis() {
        initComponents();
        this.setLocationRelativeTo(this);
        listaOpcionesResumenes();
        inicializarJList();
        this.v22 = new Ventana2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resumenesLista = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        atras = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resumenesLista.setBackground(new java.awt.Color(255, 255, 255));
        resumenesLista.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        resumenesLista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        resumenesLista.setSelectionBackground(new java.awt.Color(255, 204, 204));
        jScrollPane1.setViewportView(resumenesLista);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 330, 170));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Elija el resumen que desea analizar:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton salir.png"))); // NOI18N
        exit.setBorder(null);
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 30, -1));

        atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton atras.png"))); // NOI18N
        atras.setBorder(null);
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        jPanel1.add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        v22.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_atrasActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    
        public static int[] contarOcurrencias(String texto, Lista palabras) {
        int[] conteo = new int[palabras.getiN()];

        for (String palabra : texto.split("\\W+")) {
            for (int i = 0; i < palabras.getiN(); i++) {
                if (palabra.equalsIgnoreCase(palabras.getPosicion(i).getInfo())) {
                    conteo[i]++;
                }
            }
        }

        return conteo;
    }

    
    private void listaOpcionesResumenes(){
        
        ListaResumen resumenesEnOrden = LeerTxt.listaDeResumenes;
        
        if (resumenesEnOrden != null && resumenesEnOrden.getiN() > 0) {
            DefaultListModel<String> listModel = new DefaultListModel<>();
            NodoResumen nodoActual = resumenesEnOrden.getFirst();
            while (nodoActual != null) {
                listModel.addElement(nodoActual.getInfo().getTitulo());
                nodoActual = nodoActual.getNext();
            }
            resumenesLista.setModel(listModel);
        } else {
            DefaultListModel<String> listModel = new DefaultListModel<>();
            resumenesLista.setModel(listModel);
            JOptionPane.showMessageDialog(null, "Error.");
        }
        
        
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAnalisis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAnalisis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAnalisis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAnalisis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAnalisis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atras;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> resumenesLista;
    // End of variables declaration//GEN-END:variables
}
